# Generated by Django 4.1.4 on 2023-01-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='proile_pic',
            new_name='profile_pic',
        ),
    ]
